/**
 * COMBINED BACKEND — generated by tools/build-combined.py. DO NOT EDIT.
 * Edit the individual backend/*.gs files and re-run the build.
 * Paste this whole file into Code.gs, and backend/appsscript.json
 * into the manifest (Project Settings -> show manifest).
 */

///////////////////////////////////////////////////////////////////////////
//  Util.gs
///////////////////////////////////////////////////////////////////////////

/**
 * Util.gs — constants, schema, properties, sheet helpers, crypto helpers.
 *
 * Org model (from AWC DATA-31.07.2026.xlsx):
 *   District > Project (3: JGN/KDK/SGN) > Sector (27) > AWC (695).
 *   Field users are AWT/AWH tied to one AWC; an AWT+AWH pair usually shares
 *   the centre's phone, so PHONE IS NOT UNIQUE — identity is user_id.
 *
 * Script Properties used (set by setupAll() or manually):
 *   MASTER_ID        id of ATTENDANCE_MASTER spreadsheet
 *   PHOTOS_ROOT_ID   id of AttendancePhotos Drive folder
 *   HMAC_SECRET      random secret for session-token signing
 *   ATT_yyyy-MM      id of each monthly attendance spreadsheet
 *   GH_TOKEN         GitHub fine-grained token (contents:write on the Pages repo)
 *   GH_REPO          e.g. "someuser/attendance"
 *   GH_BRANCH        default "main"
 *   JITTER_MAX_SEC   client sync jitter ceiling, default 90
 *   USER_SEQ         id counter for console-added users (import seeds it)
 */

const TZ = 'Asia/Kolkata';
const PROPS = PropertiesService.getScriptProperties();
const CACHE = CacheService.getScriptCache();

// ---- sheet schemas (column order is the contract; never reorder) ----
const USERS_H = ['user_id', 'phone', 'name', 'cadre', 'project_code', 'sector_code', 'awc_id',
  'role', 'status', 'pin_hash', 'pin_salt', 'pin_set_at', 'failed_attempts', 'locked_until',
  'device_id', 'device_bound_at', 'created_at', 'updated_at'];
const AWC_H = ['awc_id', 'sector_code', 'project_code', 'name', 'lat', 'lng', 'radius_m', 'active'];
const PROJ_H = ['project_code', 'name'];
const SECT_H = ['sector_code', 'project_code', 'name', 'supervisor_user_id'];
const SCH_H = ['project_code', 'cadre', 'in_start', 'in_end', 'late_after', 'out_start', 'out_end'];
const SESS_H = ['token_id', 'user_id', 'device_id', 'issued_at', 'expires_at', 'revoked'];
const AUD_H = ['ts', 'actor', 'action', 'target', 'old_value', 'new_value'];
const MARKS_H = ['key', 'user_id', 'sector_code', 'cadre', 'type', 'client_ts', 'server_ts', 'skew_sec',
  'lat', 'lng', 'accuracy_m', 'geofence', 'awc_id', 'distance_m', 'photo_id',
  'device_id', 'app_version', 'net_state', 'sync_delay_sec', 'flags'];
const CORR_H = ['corr_id', 'orig_key', 'actor', 'action', 'reason', 'ts'];

// ---- policy constants ----
const PIN_ITERATIONS = 4000;      // salted SHA-256 iterations (bcrypt does not exist in Apps Script)
const TOKEN_DAYS = 30;            // session lifetime
const LOCKOUT_AFTER = 5;          // failed PINs before lockout
const LOCKOUT_MIN = 15;           // lockout duration
const GPS_UNVERIFIED_ACC_M = 250; // accuracy worse than this => UNVERIFIED
const PHOTO_RETENTION_DAYS = 45;  // per policy decision 2026-08-02
const BATCH_MAX = 20;             // max marks per sync POST
const CADRES = ['AWT', 'AWH', 'SUPERVISOR', 'CDPO', 'OTHER'];
const ROLES = ['FIELD', 'SUPERVISOR', 'CDPO', 'ADMIN'];

const U_ = headerIndex_(USERS_H);

function headerIndex_(headers) {
  const ix = {};
  headers.forEach((h, i) => { ix[h] = i; });
  return ix;
}

function rowToObj_(headers, row) {
  const o = {};
  headers.forEach((h, i) => { o[h] = row[i]; });
  return o;
}

// ---- responses & time ----
function jsonOut_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

function fmtIso_(ms) { return Utilities.formatDate(new Date(ms), TZ, "yyyy-MM-dd'T'HH:mm:ssXXX"); }
function nowIso_() { return fmtIso_(Date.now()); }
function fmtDay_(ms) { return Utilities.formatDate(new Date(ms), TZ, 'yyyy-MM-dd'); }

/** "HH:mm" (or a Sheets time-of-day Date) -> minutes since midnight, or null. */
function hmToMin_(v) {
  const s = hmStr_(v);
  const m = s.match(/^(\d{1,2}):(\d{2})/);
  return m ? Number(m[1]) * 60 + Number(m[2]) : null;
}

function hmStr_(v) {
  if (v instanceof Date) return Utilities.formatDate(v, TZ, 'HH:mm');
  return String(v == null ? '' : v).trim();
}

function pad_(n, width) { return String(n).padStart(width, '0'); }

// ---- crypto ----
function toHex_(bytes) {
  return bytes.map(b => ((b + 256) % 256).toString(16).padStart(2, '0')).join('');
}

/** Salted, iterated SHA-256. Fixed iteration count so hashes stay verifiable. */
function hashPin_(pin, salt) {
  let bytes = Utilities.newBlob(salt + ':' + pin).getBytes();
  for (let i = 0; i < PIN_ITERATIONS; i++) {
    bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, bytes);
  }
  return toHex_(bytes);
}

function hmac_(payload) {
  return toHex_(Utilities.computeHmacSha256Signature(payload, PROPS.getProperty('HMAC_SECRET')));
}

// ---- master spreadsheet access ----
function masterSS_() { return SpreadsheetApp.openById(PROPS.getProperty('MASTER_ID')); }

/** First row (1-based) in `sheet` whose column `colIndex1` equals `value` exactly; 0 if none. */
function findRowByValue_(sheet, colIndex1, value) {
  const last = sheet.getLastRow();
  if (last < 2) return 0;
  const hit = sheet.getRange(2, colIndex1, last - 1, 1)
    .createTextFinder(String(value)).matchEntireCell(true).findNext();
  return hit ? hit.getRow() : 0;
}

/** All matching row numbers. */
function findRowsByValue_(sheet, colIndex1, value) {
  const last = sheet.getLastRow();
  if (last < 2) return [];
  return sheet.getRange(2, colIndex1, last - 1, 1)
    .createTextFinder(String(value)).matchEntireCell(true).findAll()
    .map(r => r.getRow());
}

// ---- users ----
function userAtRow_(sh, row) {
  const o = rowToObj_(USERS_H, sh.getRange(row, 1, 1, USERS_H.length).getValues()[0]);
  o._row = row;
  return o;
}

/**
 * ALL users registered under a phone. AWT+AWH pairs share the centre phone
 * (190 of 695 AWCs in the source data), so this is a list, never a single row.
 */
function getUsersByPhone_(phone) {
  const sh = masterSS_().getSheetByName('Users');
  return findRowsByValue_(sh, U_.phone + 1, phone).map(r => userAtRow_(sh, r));
}

function getUserById_(id) {
  const c = CACHE.get('uid_' + id);
  if (c) return JSON.parse(c);
  const sh = masterSS_().getSheetByName('Users');
  const row = findRowByValue_(sh, U_.user_id + 1, id);
  if (!row) return null;
  const u = userAtRow_(sh, row);
  CACHE.put('uid_' + id, JSON.stringify(u), 300);
  return u;
}

function updateUser_(user, updates) {
  const sh = masterSS_().getSheetByName('Users');
  const row = user._row || findRowByValue_(sh, U_.user_id + 1, user.user_id);
  Object.keys(updates).forEach(k => {
    sh.getRange(row, U_[k] + 1).setValue(updates[k]);
    user[k] = updates[k];
  });
  sh.getRange(row, U_.updated_at + 1).setValue(nowIso_());
  CACHE.remove('uid_' + user.user_id);
}

function getUsersAll_() {
  const sh = masterSS_().getSheetByName('Users');
  const last = sh.getLastRow();
  if (last < 2) return [];
  return sh.getRange(2, 1, last - 1, USERS_H.length).getValues().map((r, i) => {
    const o = rowToObj_(USERS_H, r);
    o._row = i + 2;
    return o;
  });
}

// ---- org: projects, sectors, AWCs (all cached) ----
function getProjects_() {
  const c = CACHE.get('projects');
  if (c) return JSON.parse(c);
  const sh = masterSS_().getSheetByName('Projects');
  const last = sh.getLastRow();
  const out = last < 2 ? [] : sh.getRange(2, 1, last - 1, PROJ_H.length).getValues()
    .map(r => ({ code: String(r[0]), name: String(r[1]) }));
  CACHE.put('projects', JSON.stringify(out), 600);
  return out;
}

function getSectors_() {
  const c = CACHE.get('sectors');
  if (c) return JSON.parse(c);
  const sh = masterSS_().getSheetByName('Sectors');
  const last = sh.getLastRow();
  const out = last < 2 ? [] : sh.getRange(2, 1, last - 1, SECT_H.length).getValues()
    .map(r => ({ code: String(r[0]), project: String(r[1]), name: String(r[2]), sup: String(r[3]) }));
  CACHE.put('sectors', JSON.stringify(out), 600);
  return out;
}

function awcFromRow_(r) {
  return { awc_id: String(r[0]), sector: String(r[1]), project: String(r[2]), name: String(r[3]),
    lat: r[4] === '' || r[4] == null ? null : Number(r[4]),
    lng: r[5] === '' || r[5] == null ? null : Number(r[5]),
    radius_m: Number(r[6]) || 200, active: String(r[7]) !== 'FALSE' };
}

function getAwc_(awcId) {
  if (!awcId) return null;
  const c = CACHE.get('awc_' + awcId);
  if (c) return JSON.parse(c);
  const sh = masterSS_().getSheetByName('AWCs');
  const row = findRowByValue_(sh, 1, awcId);
  if (!row) return null;
  const a = awcFromRow_(sh.getRange(row, 1, 1, AWC_H.length).getValues()[0]);
  CACHE.put('awc_' + awcId, JSON.stringify(a), 600);
  return a;
}

/** Active AWCs of one sector (~15–40 rows; cached — supervisors geofence against these). */
function getSectorAwcs_(sectorCode) {
  const c = CACHE.get('sawcs_' + sectorCode);
  if (c) return JSON.parse(c);
  const sh = masterSS_().getSheetByName('AWCs');
  const out = findRowsByValue_(sh, 2, sectorCode)
    .map(r => awcFromRow_(sh.getRange(r, 1, 1, AWC_H.length).getValues()[0]))
    .filter(a => a.active);
  CACHE.put('sawcs_' + sectorCode, JSON.stringify(out), 600);
  return out;
}

/**
 * Geofence candidates for a user's marks:
 *   FIELD -> their own AWC; SUPERVISOR -> every AWC in their sector (they mark
 *   from whichever centre they are inspecting); CDPO/ADMIN -> none (UNVERIFIED).
 */
function geofenceCandidatesFor_(user) {
  const role = String(user.role);
  if (role === 'SUPERVISOR') return getSectorAwcs_(String(user.sector_code));
  const awc = getAwc_(String(user.awc_id));
  return awc && awc.active ? [awc] : [];
}

function getSchedules_() {
  const c = CACHE.get('schedules');
  if (c) return JSON.parse(c);
  const sh = masterSS_().getSheetByName('Schedules');
  const last = sh.getLastRow();
  const out = last < 2 ? [] : sh.getRange(2, 1, last - 1, SCH_H.length).getValues().map(r => ({
    project_code: String(r[0]).trim(), cadre: String(r[1]).trim(),
    in_start: hmStr_(r[2]), in_end: hmStr_(r[3]), late_after: hmStr_(r[4]),
    out_start: hmStr_(r[5]), out_end: hmStr_(r[6])
  }));
  CACHE.put('schedules', JSON.stringify(out), 600);
  return out;
}

/** Most specific matching schedule row: project+cadre > project > cadre > ALL. */
function scheduleFor_(project, cadre) {
  let best = null, bestScore = -1;
  for (const r of getSchedules_()) {
    const pOK = r.project_code === project, pAll = r.project_code === 'ALL';
    const cOK = r.cadre === cadre, cAll = r.cadre === 'ALL';
    if (!(pOK || pAll) || !(cOK || cAll)) continue;
    const score = (pOK ? 2 : 0) + (cOK ? 1 : 0);
    if (score > bestScore) { best = r; bestScore = score; }
  }
  return best;
}

// ---- geometry ----
function distM_(lat1, lng1, lat2, lng2) {
  const R = 6371000, r = Math.PI / 180;
  const dLat = (lat2 - lat1) * r, dLng = (lng2 - lng1) * r;
  const a = Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * r) * Math.cos(lat2 * r) * Math.sin(dLng / 2) ** 2;
  return Math.round(2 * R * Math.asin(Math.sqrt(a)));
}

// ---- audit ----
function audit_(actor, action, target, oldValue, newValue) {
  masterSS_().getSheetByName('Audit').appendRow([
    nowIso_(), String(actor), String(action), String(target),
    typeof oldValue === 'object' ? JSON.stringify(oldValue) : String(oldValue == null ? '' : oldValue),
    typeof newValue === 'object' ? JSON.stringify(newValue) : String(newValue == null ? '' : newValue)
  ]);
}

// ---- id sequences ----
function nextSeq_(name) {
  const lock = LockService.getScriptLock();
  lock.waitLock(5000);
  try {
    const n = Number(PROPS.getProperty(name) || '0') + 1;
    PROPS.setProperty(name, String(n));
    return n;
  } finally {
    lock.releaseLock();
  }
}

///////////////////////////////////////////////////////////////////////////
//  Auth.gs
///////////////////////////////////////////////////////////////////////////

/**
 * Auth.gs — login, PIN handling, lockout, device binding, session tokens.
 *
 * Phone is NOT unique: an AWT+AWH pair usually shares the centre's phone.
 * Login therefore resolves phone -> candidate list; when more than one active
 * user matches, the client is told CHOOSE_USER and retries with userId.
 * Each user has their own PIN and their own device binding; two users bound
 * to the same physical phone is the normal case, not an error.
 *
 * Token format: base64url(tokenId|userId|deviceId|expiryMs) + '.' + hmacHex.
 * Verification is stateless (signature + expiry); the Sessions sheet exists
 * only for revocation, and revocation checks are cached for 6 hours.
 */

function apiLogin_(req) {
  const phone = String(req.phone || '').trim();
  const deviceId = String(req.deviceId || '').trim();
  if (!/^\d{10}$/.test(phone)) return { ok: false, code: 'BAD_PHONE' };
  if (!deviceId) return { ok: false, code: 'NO_DEVICE' };

  // Cheap brute-force damper in front of the per-user lockout.
  const rlKey = 'lg_' + phone;
  const attempts = Number(CACHE.get(rlKey) || '0');
  if (attempts >= 20) return { ok: false, code: 'RATE_LIMIT' };
  CACHE.put(rlKey, String(attempts + 1), 3600);

  const candidates = getUsersByPhone_(phone).filter(u => u.status === 'ACTIVE');
  if (!candidates.length) return { ok: false, code: 'NO_USER' };

  let user;
  if (candidates.length === 1) {
    user = candidates[0];
  } else {
    const wantId = String(req.userId || '');
    user = candidates.find(u => String(u.user_id) === wantId);
    if (!user) {
      // Names shown pre-PIN, but only to someone holding the centre's own
      // number, and rate-limited above. Nothing beyond name + cadre leaks.
      return {
        ok: false, code: 'CHOOSE_USER',
        users: candidates.map(u => ({ id: String(u.user_id), name: String(u.name), cadre: String(u.cadre) }))
      };
    }
  }

  if (user.locked_until && new Date(user.locked_until).getTime() > Date.now()) {
    return { ok: false, code: 'LOCKED', until: String(user.locked_until) };
  }

  if (!user.pin_hash) {
    // First login (or after supervisor PIN reset): user sets their own PIN.
    const newPin = String(req.newPin || '');
    if (!newPin) return { ok: false, code: 'SET_PIN_REQUIRED', userId: String(user.user_id) };
    if (!/^\d{4}$/.test(newPin)) return { ok: false, code: 'BAD_PIN_FORMAT' };
    const salt = Utilities.getUuid();
    updateUser_(user, {
      pin_hash: hashPin_(newPin, salt), pin_salt: salt, pin_set_at: nowIso_(),
      failed_attempts: '0', locked_until: ''
    });
    audit_(user.user_id, 'PIN_SET', user.user_id, '', '');
  } else {
    const pin = String(req.pin || '');
    if (!pin) return { ok: false, code: 'PIN_REQUIRED' };
    if (hashPin_(pin, String(user.pin_salt)) !== String(user.pin_hash)) {
      const fails = (Number(user.failed_attempts) || 0) + 1;
      if (fails >= LOCKOUT_AFTER) {
        const until = fmtIso_(Date.now() + LOCKOUT_MIN * 60000);
        updateUser_(user, { failed_attempts: '0', locked_until: until });
        audit_(user.user_id, 'PIN_LOCKOUT', user.user_id, '', until);
        return { ok: false, code: 'LOCKED', until: until };
      }
      updateUser_(user, { failed_attempts: String(fails) });
      return { ok: false, code: 'WRONG_PIN', left: LOCKOUT_AFTER - fails };
    }
    if (Number(user.failed_attempts) > 0) updateUser_(user, { failed_attempts: '0', locked_until: '' });
  }

  // Device binding — one active device per FIELD user (anti-buddy-punching),
  // rebinds only via admin. The same deviceId bound to several users (shared
  // centre phone) is fine. Console roles (ADMIN/CDPO/SUPERVISOR) are exempt:
  // they legitimately sign in from office PC, laptop and phone browser.
  if (String(user.role) === 'FIELD') {
    if (user.device_id && user.device_id !== deviceId) {
      return { ok: false, code: 'DEVICE_MISMATCH' };
    }
    if (!user.device_id) {
      updateUser_(user, { device_id: deviceId, device_bound_at: nowIso_() });
      audit_(user.user_id, 'DEVICE_BIND', user.user_id, '', deviceId);
    }
  }

  CACHE.remove(rlKey);
  const token = issueToken_(user, deviceId);
  return { ok: true, token: token, config: getConfigFor_(user) };
}

function issueToken_(user, deviceId) {
  const tokenId = Utilities.getUuid();
  const exp = Date.now() + TOKEN_DAYS * 86400000;
  const payload = [tokenId, user.user_id, deviceId, exp].join('|');
  const token = Utilities.base64EncodeWebSafe(payload) + '.' + hmac_(payload);
  const lock = LockService.getScriptLock();
  let locked = false;
  try { lock.waitLock(5000); locked = true; } catch (e) { /* still append; logins are rare */ }
  try {
    masterSS_().getSheetByName('Sessions')
      .appendRow([tokenId, user.user_id, deviceId, nowIso_(), fmtIso_(exp), '']);
  } finally {
    if (locked) lock.releaseLock();
  }
  CACHE.put('sessok_' + tokenId, '1', 21600);
  return token;
}

function verifyToken_(token) {
  if (!token) return { ok: false, code: 'AUTH' };
  const parts = String(token).split('.');
  if (parts.length !== 2) return { ok: false, code: 'AUTH' };
  let payload;
  try {
    payload = Utilities.newBlob(Utilities.base64DecodeWebSafe(parts[0])).getDataAsString();
  } catch (e) {
    return { ok: false, code: 'AUTH' };
  }
  if (hmac_(payload) !== parts[1]) return { ok: false, code: 'AUTH' };
  const seg = payload.split('|');
  if (seg.length !== 4) return { ok: false, code: 'AUTH' };
  const tokenId = seg[0], userId = seg[1], deviceId = seg[2], exp = Number(seg[3]);
  if (!(exp > Date.now())) return { ok: false, code: 'EXPIRED' };

  if (!CACHE.get('sessok_' + tokenId)) {
    const sh = masterSS_().getSheetByName('Sessions');
    const row = findRowByValue_(sh, 1, tokenId);
    if (!row) return { ok: false, code: 'AUTH' };
    if (String(sh.getRange(row, 6).getValue()) === 'TRUE') return { ok: false, code: 'REVOKED' };
    CACHE.put('sessok_' + tokenId, '1', 21600);
  }

  const user = getUserById_(userId);
  if (!user || user.status !== 'ACTIVE') return { ok: false, code: 'AUTH' };
  if (String(user.role) === 'FIELD' && user.device_id && user.device_id !== deviceId) {
    return { ok: false, code: 'DEVICE_MISMATCH' };
  }
  return { ok: true, tokenId: tokenId, userId: userId, deviceId: deviceId, user: user };
}

function revokeUserSessions_(userId) {
  const sh = masterSS_().getSheetByName('Sessions');
  findRowsByValue_(sh, 2, userId).forEach(row => {
    sh.getRange(row, 6).setValue('TRUE');
    CACHE.remove('sessok_' + String(sh.getRange(row, 1).getValue()));
  });
}

function apiLogout_(auth, req) {
  const sh = masterSS_().getSheetByName('Sessions');
  const row = findRowByValue_(sh, 1, auth.tokenId);
  if (row) sh.getRange(row, 6).setValue('TRUE');
  CACHE.remove('sessok_' + auth.tokenId);
  return { ok: true };
}

function getConfigFor_(user) {
  const awc = getAwc_(String(user.awc_id));
  return {
    user: {
      id: String(user.user_id), name: String(user.name), cadre: String(user.cadre),
      project: String(user.project_code), sector: String(user.sector_code),
      awcId: String(user.awc_id), awcName: awc ? awc.name : '', role: String(user.role)
    },
    locations: geofenceCandidatesFor_(user).map(a => ({
      awc_id: a.awc_id, name: a.name, lat: a.lat, lng: a.lng, radius_m: a.radius_m
    })),
    schedule: scheduleFor_(String(user.project_code), String(user.cadre)),
    sync: { jitterMaxSec: Number(PROPS.getProperty('JITTER_MAX_SEC') || 90), batchMax: BATCH_MAX },
    photoMaxKB: 60,
    privacyVersion: 1,
    serverTs: nowIso_()
  };
}

function apiConfig_(auth, req) {
  return { ok: true, config: getConfigFor_(auth.user) };
}

///////////////////////////////////////////////////////////////////////////
//  Marks.gs
///////////////////////////////////////////////////////////////////////////

/**
 * Marks.gs — the write path: batched sync with idempotency, LockService,
 * geofence classification, anti-fraud flags, photo storage, monthly rollover.
 * Plus the token-checked photo proxy and the user's own history.
 */

/**
 * action: "sync"
 * req: { token, deviceNow: epochMs, records: [{ key, clientTs, lat, lng,
 *        accuracy, photoB64, deviceId, appVersion, netState }] }
 * Key format: {user_id}_{yyyymmdd}_{IN|OUT} — deterministic, so the
 * one-IN-one-OUT-per-day rule IS the dedupe rule.
 */
function apiSync_(auth, req) {
  const user = auth.user;
  const records = req.records || [];
  if (!records.length) return { ok: true, acks: [], serverTs: nowIso_() };
  if (records.length > BATCH_MAX) return { ok: false, code: 'BATCH_TOO_BIG' };

  const serverMs = Date.now();
  const deviceNowMs = Number(req.deviceNow) || 0;
  const skewSec = deviceNowMs ? Math.round((serverMs - deviceNowMs) / 1000) : '';

  const acks = [];
  const prepared = [];
  for (const rec of records) {
    const key = String(rec.key || '');
    const m = key.match(/^(U\d+)_(\d{8})_(IN|OUT)$/);
    if (!m || m[1] !== String(user.user_id)) {
      // A client may only ever write its own marks — enforced from the token.
      // On a shared centre phone each user syncs under their own session.
      acks.push({ key: key, status: 'REJECTED' });
      continue;
    }
    if (CACHE.get('mk_' + key)) {
      acks.push({ key: key, status: 'DUP' });
      continue;
    }
    prepared.push({ rec: rec, key: key, dateStr: m[2], type: m[3] });
  }

  // Photos go to Drive BEFORE we take the lock — Drive writes don't contend,
  // and a failed photo upload must never block the attendance record.
  for (const it of prepared) {
    it.photoId = '';
    it.photoFlag = '';
    if (it.rec.photoB64) {
      try {
        it.photoId = storePhoto_(it.dateStr, it.key, String(it.rec.photoB64));
      } catch (err) {
        it.photoFlag = 'UPLOAD_FAILED';
      }
    } else {
      it.photoFlag = 'NO_PHOTO';
    }
  }

  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
  } catch (err) {
    // Client keeps the records queued and retries with backoff. Nothing lost.
    return { ok: false, code: 'BUSY', retryable: true };
  }

  try {
    const byMonth = {};
    prepared.forEach(it => {
      const ym = it.dateStr.slice(0, 4) + '-' + it.dateStr.slice(4, 6);
      (byMonth[ym] = byMonth[ym] || []).push(it);
    });
    Object.keys(byMonth).forEach(ym => {
      const ss = getMonthSS_(ym);
      const sh = ss.getSheetByName('Marks');
      const rows = [];
      byMonth[ym].forEach(it => {
        if (findRowByValue_(sh, 1, it.key)) {
          acks.push({ key: it.key, status: 'DUP' });
        } else {
          rows.push(buildMarkRow_(user, it, skewSec, serverMs));
          acks.push({ key: it.key, status: 'OK' });
        }
        CACHE.put('mk_' + it.key, '1', 21600);
      });
      if (rows.length) {
        sh.getRange(sh.getLastRow() + 1, 1, rows.length, MARKS_H.length).setValues(rows);
      }
    });
  } finally {
    lock.releaseLock();
  }
  return { ok: true, acks: acks, serverTs: nowIso_() };
}

function buildMarkRow_(user, it, skewSec, serverMs) {
  const rec = it.rec;
  const hasFix = rec.lat != null && rec.lat !== '' && rec.lng != null && rec.lng !== '';
  const lat = hasFix ? Number(Number(rec.lat).toFixed(6)) : '';
  const lng = hasFix ? Number(Number(rec.lng).toFixed(6)) : '';
  const acc = rec.accuracy != null && rec.accuracy !== '' ? Math.round(Number(rec.accuracy)) : '';

  const gf = classifyGeofence_(user, hasFix ? lat : null, hasFix ? lng : null, acc === '' ? null : acc);

  const flags = [];
  if (it.photoFlag) flags.push(it.photoFlag);

  const clientMs = new Date(String(rec.clientTs || '')).getTime();
  const syncDelay = isNaN(clientMs) ? '' : Math.max(0, Math.round((serverMs - clientMs) / 1000));
  if (syncDelay !== '' && syncDelay > 86400) flags.push('LATE_SYNC');
  if (skewSec !== '' && Math.abs(skewSec) > 300) flags.push('CLOCK_SKEW');
  if (acc !== '' && acc > 0 && acc <= 3) flags.push('PERFECT_ACCURACY');

  // Velocity + repeated-coordinates checks against the user's previous mark
  // (cached 6 h; the nightly job re-runs these across the whole month).
  if (hasFix) {
    const prevRaw = CACHE.get('lastm_' + user.user_id);
    if (prevRaw) {
      const prev = JSON.parse(prevRaw);
      if (prev.lat === lat && prev.lng === lng) flags.push('REPEAT_COORDS');
      if (!isNaN(clientMs) && prev.ms && clientMs > prev.ms) {
        const kmh = (distM_(prev.lat, prev.lng, lat, lng) / 1000) / ((clientMs - prev.ms) / 3600000);
        if (kmh > 150) flags.push('IMPOSSIBLE_VELOCITY');
      }
    }
    CACHE.put('lastm_' + user.user_id,
      JSON.stringify({ lat: lat, lng: lng, ms: isNaN(clientMs) ? 0 : clientMs }), 21600);
  }

  return [
    it.key, String(user.user_id), String(user.sector_code), String(user.cadre), it.type,
    String(rec.clientTs || ''), fmtIso_(serverMs), skewSec,
    lat, lng, acc, gf.status, gf.awcId, gf.dist, it.photoId,
    String(rec.deviceId || ''), String(rec.appVersion || ''), String(rec.netState || ''),
    syncDelay, flags.join(',')
  ];
}

/**
 * INSIDE / OUTSIDE / UNVERIFIED against the user's geofence candidates:
 * a field user's own AWC, or every AWC in a supervisor's sector. AWCs whose
 * coordinates were blanked at import (out-of-district errors) drop out of the
 * candidate list, so marks there classify UNVERIFIED — never falsely OUTSIDE.
 */
function classifyGeofence_(user, lat, lng, acc) {
  if (lat == null || lng == null) return { status: 'UNVERIFIED', awcId: '', dist: '' };
  if (acc != null && acc > GPS_UNVERIFIED_ACC_M) return { status: 'UNVERIFIED', awcId: '', dist: '' };
  const awcs = geofenceCandidatesFor_(user).filter(a => a.lat != null && a.lng != null);
  if (!awcs.length) return { status: 'UNVERIFIED', awcId: '', dist: '' };
  let best = null, bestDist = Infinity;
  for (const a of awcs) {
    const d = distM_(lat, lng, a.lat, a.lng);
    if (d < bestDist) { bestDist = d; best = a; }
  }
  return {
    status: bestDist <= best.radius_m ? 'INSIDE' : 'OUTSIDE',
    awcId: best.awc_id,
    dist: bestDist
  };
}

// ---- photo storage ----
function storePhoto_(dateStr, key, b64) {
  const clean = b64.replace(/^data:image\/\w+;base64,/, '');
  const blob = Utilities.newBlob(Utilities.base64Decode(clean), 'image/jpeg', key + '.jpg');
  const day = dateStr.slice(0, 4) + '-' + dateStr.slice(4, 6) + '-' + dateStr.slice(6, 8);
  return getDailyFolder_(day).createFile(blob).getId();
}

function getDailyFolder_(day) {
  const c = CACHE.get('pf_' + day);
  if (c) return DriveApp.getFolderById(c);
  const root = DriveApp.getFolderById(PROPS.getProperty('PHOTOS_ROOT_ID'));
  const existing = root.getFoldersByName(day);
  const folder = existing.hasNext() ? existing.next() : root.createFolder(day);
  CACHE.put('pf_' + day, folder.getId(), 21600);
  return folder;
}

// ---- monthly rollover ----
/**
 * Returns (and lazily creates) the ATT_yyyy-MM spreadsheet.
 * NOT internally locked: the sync path already holds the script lock when it
 * gets here (LockService locks are not reentrant); trigger paths must acquire
 * the lock before calling with creation enabled.
 */
function getMonthSS_(ym, noCreate) {
  const prop = 'ATT_' + ym;
  let id = PROPS.getProperty(prop);
  if (id) return SpreadsheetApp.openById(id);
  if (noCreate) return null;

  const ss = SpreadsheetApp.create('ATT_' + ym.replace('-', '_'));
  ss.setSpreadsheetTimeZone(TZ);
  const marks = ss.insertSheet('Marks');
  marks.getRange(1, 1, 1, MARKS_H.length).setValues([MARKS_H]);
  marks.getRange('A:T').setNumberFormat('@');
  const corr = ss.insertSheet('Corrections');
  corr.getRange(1, 1, 1, CORR_H.length).setValues([CORR_H]);
  corr.getRange('A:F').setNumberFormat('@');
  const meta = ss.insertSheet('Meta');
  meta.getRange(1, 1, 2, 2).setValues([['today_date', ''], ['today_start_row', '2']]);
  const def = ss.getSheetByName('Sheet1');
  if (def) ss.deleteSheet(def);
  PROPS.setProperty(prop, ss.getId());
  return ss;
}

// ---- photo proxy (the only non-static console read besides admin actions) ----
function apiPhoto_(params) {
  const auth = verifyToken_(params.token);
  if (!auth.ok) return jsonOut_(auth);
  const fileId = String(params.id || '');
  if (!fileId) return jsonOut_({ ok: false, code: 'NO_ID' });

  let file;
  try {
    file = DriveApp.getFileById(fileId);
  } catch (e) {
    return jsonOut_({ ok: false, code: 'NOT_FOUND' });
  }
  // The file must live inside our photos tree — this endpoint runs as the
  // owner, so without this check any Drive file id would be readable.
  const parents = file.getParents();
  if (!parents.hasNext()) return jsonOut_({ ok: false, code: 'FORBIDDEN' });
  const dayFolder = parents.next();
  const gp = dayFolder.getParents();
  if (!gp.hasNext() || gp.next().getId() !== PROPS.getProperty('PHOTOS_ROOT_ID')) {
    return jsonOut_({ ok: false, code: 'FORBIDDEN' });
  }

  const targetUid = file.getName().split('_')[0];
  const viewer = auth.user;
  if (viewer.role === 'FIELD' && targetUid !== String(viewer.user_id)) {
    return jsonOut_({ ok: false, code: 'FORBIDDEN' });
  }
  if (viewer.role === 'SUPERVISOR' || viewer.role === 'CDPO') {
    const target = getUserById_(targetUid);
    if (!target || !inScope_(viewer, target)) {
      return jsonOut_({ ok: false, code: 'FORBIDDEN' });
    }
  }
  return jsonOut_({ ok: true, mime: 'image/jpeg', b64: Utilities.base64Encode(file.getBlob().getBytes()) });
}

// ---- own history (used after reinstall; day-to-day history is client-local) ----
function apiMyHistory_(auth, req) {
  const now = new Date();
  const yms = [Utilities.formatDate(now, TZ, 'yyyy-MM')];
  const prevYm = Utilities.formatDate(new Date(now.getTime() - 32 * 86400000), TZ, 'yyyy-MM');
  if (prevYm !== yms[0]) yms.push(prevYm);

  const out = [];
  for (const ym of yms) {
    const ss = getMonthSS_(ym, true);
    if (!ss) continue;
    const sh = ss.getSheetByName('Marks');
    const rows = findRowsByValue_(sh, 2, auth.userId).slice(-80);
    for (const r of rows) {
      const o = rowToObj_(MARKS_H, sh.getRange(r, 1, 1, MARKS_H.length).getValues()[0]);
      out.push({
        key: String(o.key), type: String(o.type), clientTs: String(o.client_ts),
        gf: String(o.geofence), flags: String(o.flags)
      });
    }
  }
  return { ok: true, marks: out };
}

///////////////////////////////////////////////////////////////////////////
//  Admin.gs
///////////////////////////////////////////////////////////////////////////

/**
 * Admin.gs — master-data management, adjudication, PIN/device resets.
 * Every mutation is audit-logged. Authorisation is enforced HERE, server-side,
 * from the token's user — never from anything the client sends.
 *
 * Scopes: SUPERVISOR = own sector (FIELD users only). CDPO = own project
 * (FIELD + SUPERVISOR users). ADMIN = everything.
 */

function isConsoleRole_(u) { return u.role === 'SUPERVISOR' || u.role === 'CDPO' || u.role === 'ADMIN'; }
function deny_() { return { ok: false, code: 'FORBIDDEN' }; }

function inScope_(actor, target) {
  if (actor.role === 'ADMIN') return true;
  if (actor.role === 'CDPO') {
    return String(target.project_code) === String(actor.project_code) &&
      (String(target.role) === 'FIELD' || String(target.role) === 'SUPERVISOR');
  }
  if (actor.role === 'SUPERVISOR') {
    return String(target.sector_code) === String(actor.sector_code) && String(target.role) === 'FIELD';
  }
  return false;
}

/** Sectors the actor may see; null = all. */
function sectorScope_(actor) {
  if (actor.role === 'ADMIN') return null;
  if (actor.role === 'CDPO') {
    return getSectors_().filter(s => s.project === String(actor.project_code)).map(s => s.code);
  }
  return [String(actor.sector_code)];
}

// ---- console bootstrap: users + org, scoped to the viewer ----
function apiNameMap_(auth, req) {
  if (!isConsoleRole_(auth.user)) return deny_();
  const scope = sectorScope_(auth.user);
  const map = {};
  getUsersAll_().forEach(u => {
    if (scope && scope.indexOf(String(u.sector_code)) < 0 && String(u.user_id) !== String(auth.userId)) return;
    map[String(u.user_id)] = {
      n: String(u.name), p: String(u.phone), c: String(u.cadre),
      pj: String(u.project_code), sc: String(u.sector_code), a: String(u.awc_id),
      r: String(u.role), s: String(u.status)
    };
  });
  const awcs = {};
  masterSheetRows_('AWCs', AWC_H).forEach(r => {
    const a = awcFromRow_(r);
    if (scope && scope.indexOf(a.sector) < 0) return;
    awcs[a.awc_id] = { n: a.name, sc: a.sector, pj: a.project, lat: a.lat, lng: a.lng, r: a.radius_m };
  });
  return {
    ok: true, users: map, awcs: awcs,
    projects: getProjects_(),
    sectors: scope ? getSectors_().filter(s => scope.indexOf(s.code) >= 0) : getSectors_()
  };
}

function masterSheetRows_(name, headers) {
  const sh = masterSS_().getSheetByName(name);
  const last = sh.getLastRow();
  return last < 2 ? [] : sh.getRange(2, 1, last - 1, headers.length).getValues();
}

// ---- adjudication: corrections are APPENDED, Marks rows are never touched ----
function apiCorrection_(auth, req) {
  if (!isConsoleRole_(auth.user)) return deny_();
  const origKey = String(req.origKey || '');
  const action = String(req.act || '');
  const reason = String(req.reason || '').slice(0, 300);
  if (['ACCEPT_OUTSIDE', 'REJECT_MARK', 'MANUAL_MARK'].indexOf(action) < 0) {
    return { ok: false, code: 'BAD_ACTION' };
  }
  const m = origKey.match(/^(U\d+)_(\d{8})_(IN|OUT)$/);
  if (!m) return { ok: false, code: 'BAD_KEY' };
  if (!reason) return { ok: false, code: 'REASON_REQUIRED' };

  const target = getUserById_(m[1]);
  if (!target || !inScope_(auth.user, target)) return deny_();

  const ym = m[2].slice(0, 4) + '-' + m[2].slice(4, 6);
  const ss = getMonthSS_(ym, true);
  if (!ss) return { ok: false, code: 'NO_MONTH' };
  ss.getSheetByName('Corrections').appendRow([
    Utilities.getUuid(), origKey, String(auth.userId), action, reason, nowIso_()
  ]);
  audit_(auth.userId, 'MARK_' + action, origKey, '', reason);
  return { ok: true };
}

// ---- supervisor-mediated resets (the no-SMS forgot-PIN flow) ----
// Targets are user_id, never phone — phones are shared between AWT/AWH pairs.
function apiPinReset_(auth, req) {
  if (!isConsoleRole_(auth.user)) return deny_();
  const target = getUserById_(String(req.userId || ''));
  if (!target || !inScope_(auth.user, target)) return deny_();
  updateUser_(target, { pin_hash: '', pin_salt: '', failed_attempts: '0', locked_until: '' });
  revokeUserSessions_(target.user_id);
  audit_(auth.userId, 'PIN_RESET', target.user_id, '', '');
  return { ok: true, userId: String(target.user_id) };
}

function apiDeviceUnbind_(auth, req) {
  if (!isConsoleRole_(auth.user)) return deny_();
  const target = getUserById_(String(req.userId || ''));
  if (!target || !inScope_(auth.user, target)) return deny_();
  const old = String(target.device_id);
  updateUser_(target, { device_id: '', device_bound_at: '' });
  revokeUserSessions_(target.user_id);
  audit_(auth.userId, 'DEVICE_REBIND_APPROVED', target.user_id, old, '');
  return { ok: true, userId: String(target.user_id) };
}

// ---- geofence re-capture in the field (supervisor stands at the AWC) ----
// This is how the coords blanked at import (out-of-district errors) get fixed.
function apiSetAwcCoords_(auth, req) {
  if (!isConsoleRole_(auth.user)) return deny_();
  const awcId = String(req.awcId || '');
  const sh = masterSS_().getSheetByName('AWCs');
  const row = findRowByValue_(sh, 1, awcId);
  if (!row) return { ok: false, code: 'NOT_FOUND' };
  const awc = awcFromRow_(sh.getRange(row, 1, 1, AWC_H.length).getValues()[0]);
  const scope = sectorScope_(auth.user);
  if (scope && scope.indexOf(awc.sector) < 0) return deny_();
  const lat = Number(req.lat), lng = Number(req.lng);
  if (!isFinite(lat) || !isFinite(lng)) return { ok: false, code: 'BAD_COORDS' };
  const old = { lat: awc.lat, lng: awc.lng, radius_m: awc.radius_m };
  sh.getRange(row, 5, 1, 3).setValues([[lat, lng, Number(req.radius) || awc.radius_m || 200]]);
  CACHE.remove('awc_' + awcId);
  CACHE.remove('sawcs_' + awc.sector);
  audit_(auth.userId, 'AWC_COORDS_SET', awcId, old, { lat: lat, lng: lng, radius_m: Number(req.radius) || awc.radius_m });
  return { ok: true, awcId: awcId };
}

// ---- admin-only master data ----
function apiUserUpsert_(auth, req) {
  if (auth.user.role !== 'ADMIN') return deny_();
  const r = upsertUser_(req.user || {}, auth.userId);
  return r.error ? { ok: false, code: r.error } : { ok: true, userId: r.userId };
}

function apiImportUsers_(auth, req) {
  if (auth.user.role !== 'ADMIN') return deny_();
  const rows = req.rows || [];
  if (rows.length > 200) return { ok: false, code: 'CHUNK_TOO_BIG', max: 200 };
  const results = [];
  rows.forEach(row => {
    const r = upsertUser_(row, auth.userId);
    results.push(r.error ? { name: row.name, error: r.error } : { name: row.name, userId: r.userId });
  });
  return { ok: true, results: results };
}

function apiSetSchedules_(auth, req) {
  if (auth.user.role !== 'ADMIN') return deny_();
  const rows = (req.rows || []).map(r => [
    String(r.project_code || 'ALL'), String(r.cadre || 'ALL'),
    hmStr_(r.in_start), hmStr_(r.in_end), hmStr_(r.late_after),
    hmStr_(r.out_start), hmStr_(r.out_end)
  ]);
  if (!rows.length) return { ok: false, code: 'EMPTY' };
  const sh = masterSS_().getSheetByName('Schedules');
  const old = sh.getLastRow() >= 2 ? sh.getRange(2, 1, sh.getLastRow() - 1, SCH_H.length).getValues() : [];
  if (sh.getLastRow() >= 2) sh.getRange(2, 1, sh.getLastRow() - 1, SCH_H.length).clearContent();
  sh.getRange(2, 1, rows.length, SCH_H.length).setValues(rows);
  CACHE.remove('schedules');
  audit_(auth.userId, 'SCHEDULES_SET', 'Schedules', old, rows);
  return { ok: true, count: rows.length };
}

function apiRevoke_(auth, req) {
  if (auth.user.role !== 'ADMIN') return deny_();
  const sh = masterSS_().getSheetByName('Sessions');
  const row = findRowByValue_(sh, 1, String(req.tokenId || ''));
  if (!row) return { ok: false, code: 'NOT_FOUND' };
  sh.getRange(row, 6).setValue('TRUE');
  CACHE.remove('sessok_' + String(req.tokenId));
  audit_(auth.userId, 'TOKEN_REVOKE', String(req.tokenId), '', '');
  return { ok: true };
}

// ---- shared internals (also used by Maintenance.importFromSheets) ----
/**
 * Create or update a user. Update targets `user_id` when given, otherwise a
 * new id is issued. Phone may be blank (7 staff in the source file have no
 * valid mobile — they exist in reports but cannot login until it is fixed).
 */
function upsertUser_(f, actor) {
  const phone = String(f.phone || '').replace(/\D/g, '');
  if (phone && !/^\d{10}$/.test(phone)) return { error: 'BAD_PHONE' };
  const cadre = String(f.cadre || '').trim().toUpperCase();
  if (CADRES.indexOf(cadre) < 0) return { error: 'BAD_CADRE' };
  const role = (String(f.role || 'FIELD').trim().toUpperCase()) || 'FIELD';
  if (ROLES.indexOf(role) < 0) return { error: 'BAD_ROLE' };
  const project = String(f.project_code || '').trim();
  const sector = String(f.sector_code || '').trim();
  const awcId = String(f.awc_id || '').trim();
  if (role === 'FIELD' && !awcId) return { error: 'NO_AWC' };
  if (role === 'SUPERVISOR' && !sector) return { error: 'NO_SECTOR' };
  if (role === 'CDPO' && !project) return { error: 'NO_PROJECT' };

  const givenId = String(f.user_id || '').trim();
  const existing = givenId ? getUserById_(givenId) : null;
  if (givenId && !existing && !f.allowCreateWithId) return { error: 'NO_SUCH_USER' };

  if (existing) {
    const old = { name: existing.name, phone: existing.phone, cadre: existing.cadre,
      project_code: existing.project_code, sector_code: existing.sector_code,
      awc_id: existing.awc_id, role: existing.role, status: existing.status };
    updateUser_(existing, {
      phone: phone, name: String(f.name || existing.name), cadre: cadre,
      project_code: project, sector_code: sector, awc_id: awcId, role: role,
      status: String(f.status || existing.status || 'ACTIVE')
    });
    audit_(actor, 'USER_UPDATE', existing.user_id, old, f);
    return { userId: String(existing.user_id) };
  }

  const userId = givenId || ('U' + pad_(nextSeq_('USER_SEQ'), 4));
  masterSS_().getSheetByName('Users').appendRow([
    userId, phone, String(f.name || ''), cadre, project, sector, awcId, role, 'ACTIVE',
    '', '', '', '0', '', '', '', nowIso_(), nowIso_()
  ]);
  audit_(actor, 'USER_ADD', userId, '', { phone: phone, name: f.name, awc: awcId, sector: sector, role: role });
  return { userId: userId };
}

///////////////////////////////////////////////////////////////////////////
//  Summary.gs
///////////////////////////////////////////////////////////////////////////

/**
 * Summary.gs — the read path. Pre-computes static JSON and commits it to the
 * GitHub Pages repo, so console dashboard reads cost ZERO Apps Script
 * executions and ZERO Sheet reads.
 *
 *  - summaryTick(): every 10 min (peak windows; hourly off-peak) -> today.json
 *  - nightlyJob(): 22:00 -> month/S##.json + exceptions.json + org.json
 *    (+ archive on the 1st)
 *
 * Published JSON is pseudonymous: user ids and AWC/sector codes only, never
 * names or phones. The console resolves names via the authenticated nameMap
 * call. org.json carries org-unit names (public facility names, no coords).
 */

function summaryTick() {
  const now = new Date();
  const h = Number(Utilities.formatDate(now, TZ, 'H'));
  const min = Number(Utilities.formatDate(now, TZ, 'm'));
  const hm = h * 60 + min;
  const peak = (hm >= 480 && hm <= 660) || (hm >= 900 && hm <= 1080); // 8:00–11:00, 15:00–18:00
  if (!peak && min >= 10) return; // off-peak: only the first tick each hour
  buildToday_();
}

function buildToday_() {
  const nowMs = Date.now();
  const today = fmtDay_(nowMs);
  const todayCompact = today.replace(/-/g, '');
  const ym = today.slice(0, 7);
  const ss = getMonthSS_(ym, true);
  if (!ss) return;

  const sh = ss.getSheetByName('Marks');
  const startRow = todayStartRow_(ss, sh, today);
  const last = sh.getLastRow();

  // Index today's marks by user. Only rows received today are read (<= ~2,500),
  // which is what keeps this run inside the trigger-minutes budget all month.
  const marksByUser = {};
  if (last >= startRow) {
    const vals = sh.getRange(startRow, 1, last - startRow + 1, MARKS_H.length).getValues();
    for (const v of vals) {
      const o = rowToObj_(MARKS_H, v);
      const p = String(o.key).split('_');
      if (p[1] !== todayCompact) continue; // late-synced older marks: nightly job covers them
      (marksByUser[String(o.user_id)] = marksByUser[String(o.user_id)] || {})[p[2]] = o;
    }
  }

  const sectorProject = {};
  getSectors_().forEach(s => { sectorProject[s.code] = s.project; });

  const users = getUsersAll_().filter(u => String(u.status) === 'ACTIVE' && String(u.role) !== 'ADMIN');
  const sectors = {};
  const userEntries = [];
  const exceptions = [];

  for (const u of users) {
    const uid = String(u.user_id), sc = String(u.sector_code);
    const agg = sectors[sc] = sectors[sc] ||
      { expected: 0, in: 0, late: 0, out: 0, notMarked: 0, outside: 0, unverified: 0 };
    agg.expected++;

    const recs = marksByUser[uid] || {};
    const sch = scheduleFor_(String(u.project_code), String(u.cadre));
    const lateMin = sch ? hmToMin_(sch.late_after) : null;

    let st = 'NOT_MARKED';
    const entry = { id: uid, s: sc, a: String(u.awc_id), st: st, in: null, out: null, gf: null, fl: '', ph: null };
    let worstGf = null;

    ['IN', 'OUT'].forEach(type => {
      const o = recs[type];
      if (!o) return;
      const t = String(o.client_ts).slice(11, 16);
      const gf = String(o.geofence);
      const fl = String(o.flags);
      if (type === 'IN') {
        entry.in = t;
        entry.ph = String(o.photo_id) || null;
        st = (lateMin != null && hmToMin_(t) != null && hmToMin_(t) > lateMin) ? 'LATE' : 'PRESENT';
        if (st === 'LATE') agg.late++; else agg.in++; // "in" = on time; late counted separately
      } else {
        entry.out = t;
        agg.out++;
      }
      if (gf === 'OUTSIDE' || (gf === 'UNVERIFIED' && worstGf !== 'OUTSIDE')) worstGf = gf;
      else if (!worstGf) worstGf = gf;
      if (fl) entry.fl = entry.fl ? entry.fl + ',' + fl : fl;
      if (gf !== 'INSIDE' || fl) {
        exceptions.push({
          key: String(o.key), u: uid, s: sc, t: type, at: t,
          gf: gf, fl: fl, ph: String(o.photo_id) || null
        });
      }
    });

    entry.st = st;
    entry.gf = worstGf;
    if (st === 'NOT_MARKED') agg.notMarked++;
    if (worstGf === 'OUTSIDE') agg.outside++;
    if (worstGf === 'UNVERIFIED') agg.unverified++;
    userEntries.push(entry);
  }

  const blank = () => ({ expected: 0, in: 0, late: 0, out: 0, notMarked: 0, outside: 0, unverified: 0 });
  const district = blank();
  const projects = {};
  Object.keys(sectors).forEach(sc => {
    const pc = sectorProject[sc] || '?';
    const p = projects[pc] = projects[pc] || blank();
    Object.keys(district).forEach(k => {
      district[k] += sectors[sc][k];
      p[k] += sectors[sc][k];
    });
  });

  const generatedAt = nowIso_();
  const todayJson = {
    generatedAt: generatedAt, date: today, district: district,
    projects: Object.keys(projects).sort().map(pc => Object.assign({ code: pc }, projects[pc])),
    sectors: Object.keys(sectors).sort().map(sc =>
      Object.assign({ code: sc, project: sectorProject[sc] || '' }, sectors[sc])),
    users: userEntries, exceptions: exceptions
  };
  ghCommit_([
    { path: 'summary/today.json', content: JSON.stringify(todayJson) },
    { path: 'summary/meta.json', content: JSON.stringify({ generatedAt: generatedAt, month: ym, date: today }) }
  ], 'today ' + generatedAt);
}

/** First Marks row received today; persisted in Meta so each tick is incremental. */
function todayStartRow_(ss, sh, today) {
  const meta = ss.getSheetByName('Meta');
  const kv = meta.getRange(1, 1, 2, 2).getValues();
  if (String(kv[0][1]) === today) return Number(kv[1][1]) || 2;

  const last = sh.getLastRow();
  let found = last + 1;
  const from = Math.max(2, last - 4000); // bounded tail scan on day change
  if (last >= 2) {
    const ts = sh.getRange(from, 7, last - from + 1, 1).getValues(); // server_ts column
    for (let i = 0; i < ts.length; i++) {
      if (String(ts[i][0]).slice(0, 10) === today) { found = from + i; break; }
    }
  }
  meta.getRange(1, 2).setValue(today);
  meta.getRange(2, 2).setValue(String(found));
  return found;
}

// ---- org structure for the console (names of org units, no coords, no people) ----
function buildOrgFile_() {
  const awcs = {};
  masterSheetRows_('AWCs', AWC_H).forEach(r => {
    const a = awcFromRow_(r);
    awcs[a.awc_id] = { n: a.name, sc: a.sector };
  });
  return {
    path: 'summary/org.json',
    content: JSON.stringify({
      generatedAt: nowIso_(),
      projects: getProjects_(),
      sectors: getSectors_().map(s => ({ code: s.code, project: s.project, name: s.name })),
      awcs: awcs
    })
  };
}

/** Owner-run after importFromSheets so the console has org names immediately. */
function publishOrg() {
  ghCommit_([buildOrgFile_()], 'org ' + nowIso_());
}

/**
 * Owner-run: force an immediate today.json publish, bypassing summaryTick's
 * off-peak gate (which otherwise defers to the first 10 minutes of the hour).
 */
function publishToday() {
  buildToday_();
}

// ---- nightly full build ----
function nightlyJob() {
  const now = new Date();
  const ym = Utilities.formatDate(now, TZ, 'yyyy-MM');
  let files = buildMonthFiles_(ym, 'summary/month/', true);
  files.push(buildOrgFile_());
  if (Utilities.formatDate(now, TZ, 'd') === '1') {
    // Freeze last month under summary/archive/ before it goes cold.
    const y = Number(ym.slice(0, 4)), m = Number(ym.slice(5, 7));
    const prevYm = m === 1 ? (y - 1) + '-12' : y + '-' + pad_(m - 1, 2);
    files = files.concat(buildMonthFiles_(prevYm, 'summary/archive/' + prevYm + '/', false));
  }
  if (files.length) ghCommit_(files, 'nightly ' + nowIso_());
}

/**
 * Reads the full month once (the only full read of the day), applies
 * corrections, detects cross-day anomalies, and emits one JSON per sector
 * plus (optionally) the open exception queue.
 */
function buildMonthFiles_(ym, basePath, withExceptions) {
  const ss = getMonthSS_(ym, true);
  if (!ss) return [];
  const sh = ss.getSheetByName('Marks');
  const last = sh.getLastRow();
  const marks = last < 2 ? [] :
    sh.getRange(2, 1, last - 1, MARKS_H.length).getValues().map(v => rowToObj_(MARKS_H, v));

  const cs = ss.getSheetByName('Corrections');
  const cLast = cs.getLastRow();
  const corrByKey = {};
  if (cLast >= 2) {
    cs.getRange(2, 1, cLast - 1, CORR_H.length).getValues().forEach(v => {
      const c = rowToObj_(CORR_H, v);
      corrByKey[String(c.orig_key)] = c; // later rows win: latest correction is authoritative
    });
  }

  const generatedAt = nowIso_();
  const bySector = {};   // sc -> uid -> dd -> {IN:{...}, OUT:{...}}
  const coordTrail = {}; // uid -> [{dd, coords}] for the static-coordinates anomaly
  const exceptions = [];

  for (const o of marks) {
    const key = String(o.key);
    const p = key.split('_');
    const uid = String(o.user_id), sc = String(o.sector_code);
    const dd = p[1].slice(6, 8), type = p[2];
    const corr = corrByKey[key];

    const cell = {
      t: String(o.client_ts).slice(11, 16),
      gf: String(o.geofence),
      d: o.distance_m === '' ? null : Number(o.distance_m),
      fl: String(o.flags),
      ph: String(o.photo_id) || null,
      x: corr ? (corr.action === 'REJECT_MARK' ? 'REJ' : corr.action === 'ACCEPT_OUTSIDE' ? 'ACC' : 'COR') : ''
    };
    const sb = bySector[sc] = bySector[sc] || {};
    const ub = sb[uid] = sb[uid] || {};
    (ub[dd] = ub[dd] || {})[type] = cell;

    if (type === 'IN' && cell.gf !== 'UNVERIFIED' && o.lat !== '' && o.lng !== '') {
      (coordTrail[uid] = coordTrail[uid] || []).push({ dd: dd, c: o.lat + ',' + o.lng, sc: sc });
    }
    if (withExceptions && !corr && (cell.gf !== 'INSIDE' || cell.fl)) {
      exceptions.push({ key: key, u: uid, s: sc, d: p[1], t: type, at: cell.t, gf: cell.gf, fl: cell.fl, ph: cell.ph });
    }
  }

  // Manual marks adjudicated in by a supervisor (orig_key that has no Marks row).
  Object.keys(corrByKey).forEach(key => {
    const c = corrByKey[key];
    if (String(c.action) !== 'MANUAL_MARK') return;
    const p = key.split('_');
    if (p.length !== 3 || p[1].slice(0, 6) !== ym.replace('-', '')) return;
    const target = getUserById_(p[0]);
    if (!target) return;
    const sc = String(target.sector_code);
    const sb = bySector[sc] = bySector[sc] || {};
    const ub = sb[p[0]] = sb[p[0]] || {};
    const dd = p[1].slice(6, 8);
    if (!(ub[dd] && ub[dd][p[2]])) {
      (ub[dd] = ub[dd] || {})[p[2]] = { t: null, gf: 'MANUAL', d: null, fl: '', ph: null, x: 'MAN' };
    }
  });

  // Anomaly: IN coordinates identical to 6 dp across >= 5 consecutive marked days.
  if (withExceptions) {
    Object.keys(coordTrail).forEach(uid => {
      const trail = coordTrail[uid].sort((a, b) => a.dd < b.dd ? -1 : 1);
      let run = 1;
      for (let i = 1; i < trail.length; i++) {
        run = trail[i].c === trail[i - 1].c ? run + 1 : 1;
        if (run === 5) {
          exceptions.push({
            key: 'ANOM_' + uid + '_' + ym, u: uid, s: trail[i].sc, d: ym.replace('-', '') + trail[i].dd,
            t: 'ANOMALY', at: null, gf: 'STATIC_COORDS', fl: 'REPEAT_COORDS_5D', ph: null
          });
          break;
        }
      }
    });
  }

  const files = Object.keys(bySector).sort().map(sc => ({
    path: basePath + sc + '.json',
    content: JSON.stringify({ ym: ym, generatedAt: generatedAt, sector: sc, users: bySector[sc] })
  }));
  if (withExceptions) {
    files.push({
      path: 'summary/exceptions.json',
      content: JSON.stringify({ ym: ym, generatedAt: generatedAt, open: exceptions })
    });
  }
  return files;
}

// ---- GitHub commit (git data API: one commit for all changed files) ----
function ghCommit_(files, msg) {
  const tok = PROPS.getProperty('GH_TOKEN');
  const repo = PROPS.getProperty('GH_REPO');
  if (!tok || !repo) {
    console.warn('GH_TOKEN / GH_REPO not set — summary not published');
    return;
  }
  const branch = PROPS.getProperty('GH_BRANCH') || 'main';
  const api = 'https://api.github.com/repos/' + repo;
  const gh = (path, method, payload) => {
    const opts = {
      method: method || 'get',
      muteHttpExceptions: true,
      headers: { Authorization: 'Bearer ' + tok, Accept: 'application/vnd.github+json' }
    };
    if (payload) {
      opts.contentType = 'application/json';
      opts.payload = JSON.stringify(payload);
    }
    const res = UrlFetchApp.fetch(api + path, opts);
    if (res.getResponseCode() >= 300) {
      throw new Error('GitHub ' + res.getResponseCode() + ' on ' + path + ': ' +
        res.getContentText().slice(0, 200));
    }
    return JSON.parse(res.getContentText());
  };

  const head = gh('/git/ref/heads/' + branch).object.sha;
  const baseTree = gh('/git/commits/' + head).tree.sha;
  const tree = gh('/git/trees', 'post', {
    base_tree: baseTree,
    tree: files.map(f => ({ path: f.path, mode: '100644', type: 'blob', content: f.content }))
  });
  const commit = gh('/git/commits', 'post', { message: msg, tree: tree.sha, parents: [head] });
  gh('/git/refs/heads/' + branch, 'patch', { sha: commit.sha });
}

///////////////////////////////////////////////////////////////////////////
//  Maintenance.gs
///////////////////////////////////////////////////////////////////////////

/**
 * Maintenance.gs — one-time setup, triggers, photo reaper, month pre-creation,
 * and the owner-run bulk import of the AWC master data.
 *
 * FIRST RUN: set Script Properties ADMIN_PHONE (10 digits) and ADMIN_NAME
 * (Project Settings > Script properties), then run setupAll() from the
 * editor. They live in properties, not code, so no real phone number is
 * ever committed to the (public) Pages repository.
 * IMPORT: paste the five tools/import-awc.py output CSVs into tabs named
 * IMPORT_PROJECTS / IMPORT_SECTORS / IMPORT_AWCS / IMPORT_USERS /
 * IMPORT_SCHEDULES in ATTENDANCE_MASTER (header rows included), run
 * importFromSheets(), then publishOrg().
 */

function setupAll() {
  const adminPhone = String(PROPS.getProperty('ADMIN_PHONE') || '').replace(/\D/g, '');
  if (!/^\d{10}$/.test(adminPhone)) {
    throw new Error('Set Script Property ADMIN_PHONE (10-digit mobile of the first admin) before running setupAll.');
  }
  if (!PROPS.getProperty('HMAC_SECRET')) {
    PROPS.setProperty('HMAC_SECRET', Utilities.getUuid() + Utilities.getUuid());
  }
  if (!PROPS.getProperty('MASTER_ID')) createMaster_();
  if (!PROPS.getProperty('PHOTOS_ROOT_ID')) {
    PROPS.setProperty('PHOTOS_ROOT_ID', DriveApp.createFolder('AttendancePhotos').getId());
  }
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    getMonthSS_(Utilities.formatDate(new Date(), TZ, 'yyyy-MM'));
  } finally {
    lock.releaseLock();
  }
  bootstrapAdmin_();
  installTriggers_();
  return 'Setup complete. MASTER_ID=' + PROPS.getProperty('MASTER_ID');
}

function createMaster_() {
  const ss = SpreadsheetApp.create('ATTENDANCE_MASTER');
  ss.setSpreadsheetTimeZone(TZ);
  const tabs = [
    ['Users', USERS_H], ['AWCs', AWC_H], ['Projects', PROJ_H], ['Sectors', SECT_H],
    ['Schedules', SCH_H], ['Sessions', SESS_H], ['Audit', AUD_H]
  ];
  tabs.forEach(t => {
    const sh = ss.insertSheet(t[0]);
    sh.getRange(1, 1, 1, t[1].length).setValues([t[1]]);
    sh.getRange(1, 1, sh.getMaxRows(), t[1].length).setNumberFormat('@'); // keep phones/ISO strings as text
  });
  const def = ss.getSheetByName('Sheet1');
  if (def) ss.deleteSheet(def);
  PROPS.setProperty('MASTER_ID', ss.getId());
}

function bootstrapAdmin_() {
  const phone = String(PROPS.getProperty('ADMIN_PHONE')).replace(/\D/g, '');
  if (getUsersByPhone_(phone).length) return;
  // Fixed id U2000, outside both the register range (U0001..) and the manual
  // console-account range (U2001..): an id-keyed import can never clobber it.
  upsertUser_({
    user_id: 'U2000', allowCreateWithId: true,
    phone: phone, name: String(PROPS.getProperty('ADMIN_NAME') || 'District Admin'),
    cadre: 'OTHER', role: 'ADMIN'
  }, 'SETUP');
}

function installTriggers_() {
  ScriptApp.getProjectTriggers().forEach(t => ScriptApp.deleteTrigger(t));
  ScriptApp.newTrigger('summaryTick').timeBased().everyMinutes(10).create();
  ScriptApp.newTrigger('nightlyJob').timeBased().atHour(22).everyDays(1).create();
  ScriptApp.newTrigger('reaperJob').timeBased().atHour(2).everyDays(1).create();
  ScriptApp.newTrigger('monthPrep').timeBased().atHour(3).everyDays(1).create();
}

/**
 * Deletes photo day-folders older than PHOTO_RETENTION_DAYS.
 * Hard-deletes via the Drive advanced service so the bytes leave the quota
 * immediately (trash counts against quota for 30 days); falls back to trash.
 * Processes at most 3 day-folders per run to stay inside the 6-min limit.
 */
function reaperJob() {
  const cutoff = fmtDay_(Date.now() - PHOTO_RETENTION_DAYS * 86400000);
  const root = DriveApp.getFolderById(PROPS.getProperty('PHOTOS_ROOT_ID'));
  const it = root.getFolders();
  const victims = [];
  while (it.hasNext()) {
    const f = it.next();
    if (/^\d{4}-\d{2}-\d{2}$/.test(f.getName()) && f.getName() < cutoff) victims.push(f);
  }
  victims.sort((a, b) => a.getName() < b.getName() ? -1 : 1);
  let done = 0;
  for (const folder of victims.slice(0, 3)) {
    try {
      const files = folder.getFiles();
      while (files.hasNext()) Drive.Files.remove(files.next().getId());
      Drive.Files.remove(folder.getId());
    } catch (e) {
      folder.setTrashed(true); // quota frees 30 days later, but retention still enforced
    }
    done++;
  }
  console.log('reaper: removed ' + done + '/' + victims.length + ' day folders older than ' + cutoff);
}

/** From the 25th, make sure next month's spreadsheet exists before it's needed. */
function monthPrep() {
  const now = new Date();
  if (Number(Utilities.formatDate(now, TZ, 'd')) < 25) return;
  const y = Number(Utilities.formatDate(now, TZ, 'yyyy'));
  const m = Number(Utilities.formatDate(now, TZ, 'M'));
  const nextYm = m === 12 ? (y + 1) + '-01' : y + '-' + pad_(m + 1, 2);
  if (PROPS.getProperty('ATT_' + nextYm)) return;
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    getMonthSS_(nextYm);
  } finally {
    lock.releaseLock();
  }
}

// ---------------------------------------------------------------------------
// Bulk import — owner-run from the editor. Idempotent: re-running with a
// corrected file updates org data and user master fields but NEVER touches
// pin_hash / device binding / status of existing users, and never deletes.
// ---------------------------------------------------------------------------

function importFromSheets() {
  const ss = masterSS_();
  const out = [];

  const readTab = (name, width) => {
    const sh = ss.getSheetByName(name);
    if (!sh || sh.getLastRow() < 2) return null;
    return sh.getRange(2, 1, sh.getLastRow() - 1, width).getValues()
      .filter(r => String(r[0]).trim());
  };

  const replaceTab = (name, headers, rows) => {
    const sh = ss.getSheetByName(name);
    if (sh.getLastRow() >= 2) sh.getRange(2, 1, sh.getLastRow() - 1, headers.length).clearContent();
    if (rows.length) sh.getRange(2, 1, rows.length, headers.length).setValues(rows);
  };

  // Projects: project_code,name
  const proj = readTab('IMPORT_PROJECTS', 2);
  if (proj) {
    replaceTab('Projects', PROJ_H, proj.map(r => [String(r[0]).trim(), String(r[1]).trim()]));
    CACHE.remove('projects');
    out.push('projects: ' + proj.length);
  }

  // Sectors: sector_code,project_code,name,supervisor_phone
  // supervisor_user_id resolves AFTER users import — run resolveSectorSupervisors() then.
  const sect = readTab('IMPORT_SECTORS', 4);
  if (sect) {
    replaceTab('Sectors', SECT_H, sect.map(r =>
      [String(r[0]).trim(), String(r[1]).trim(), String(r[2]).trim(), '']));
    CACHE.remove('sectors');
    out.push('sectors: ' + sect.length);
  }

  // AWCs: awc_id,sector_code,project_code,name,lat,lng,radius_m
  const awcs = readTab('IMPORT_AWCS', 7);
  if (awcs) {
    replaceTab('AWCs', AWC_H, awcs.map(r => [
      String(r[0]).trim(), String(r[1]).trim(), String(r[2]).trim(), String(r[3]).trim(),
      r[4] === '' || r[4] == null ? '' : Number(r[4]),
      r[5] === '' || r[5] == null ? '' : Number(r[5]),
      Number(r[6]) || 200, 'TRUE'
    ]));
    out.push('awcs: ' + awcs.length);
  }

  // Users: user_id,phone,name,cadre,role,project_code,sector_code,awc_id
  // Merged in bulk: one read, one write. Existing rows keep their auth columns.
  const usersIn = readTab('IMPORT_USERS', 8);
  if (usersIn) {
    const sh = ss.getSheetByName('Users');
    const existing = {};
    getUsersAll_().forEach(u => { existing[String(u.user_id)] = u; });

    let added = 0, updated = 0, maxSeq = Number(PROPS.getProperty('USER_SEQ') || '0');
    const errors = [];
    const newRows = [];
    for (const r of usersIn) {
      const uid = String(r[0]).trim();
      const phone = String(r[1] == null ? '' : r[1]).replace(/\D/g, '');
      const name = String(r[2]).trim();
      const cadre = String(r[3]).trim().toUpperCase();
      const role = String(r[4] || 'FIELD').trim().toUpperCase();
      if (!/^U\d{4,}$/.test(uid)) { errors.push(uid + ':BAD_ID'); continue; }
      if (phone && phone.length !== 10) { errors.push(uid + ':BAD_PHONE'); continue; }
      if (CADRES.indexOf(cadre) < 0) { errors.push(uid + ':BAD_CADRE'); continue; }
      if (ROLES.indexOf(role) < 0) { errors.push(uid + ':BAD_ROLE'); continue; }
      const fields = {
        phone: phone, name: name, cadre: cadre, role: role,
        project_code: String(r[5]).trim(), sector_code: String(r[6]).trim(),
        awc_id: String(r[7] == null ? '' : r[7]).trim()
      };
      const seqN = Number(uid.slice(1));
      if (seqN > maxSeq) maxSeq = seqN;
      const ex = existing[uid];
      if (ex) {
        const changed = Object.keys(fields).some(k => String(ex[k]) !== String(fields[k]));
        if (changed) {
          updateUser_(ex, fields);
          updated++;
        }
      } else {
        newRows.push([uid, fields.phone, fields.name, fields.cadre, fields.project_code,
          fields.sector_code, fields.awc_id, fields.role, 'ACTIVE',
          '', '', '', '0', '', '', '', nowIso_(), nowIso_()]);
        added++;
      }
    }
    if (newRows.length) {
      sh.getRange(sh.getLastRow() + 1, 1, newRows.length, USERS_H.length).setValues(newRows);
    }
    PROPS.setProperty('USER_SEQ', String(maxSeq));
    audit_('OWNER', 'USERS_IMPORT', 'Users', '', { added: added, updated: updated, errors: errors.length });
    out.push('users: ' + added + ' added, ' + updated + ' updated, errors: ' +
      (errors.length ? errors.join(', ') : 'none'));
  }

  // Schedules: project_code,cadre,in_start,in_end,late_after,out_start,out_end
  const sch = readTab('IMPORT_SCHEDULES', 7);
  if (sch) {
    const res = apiSetSchedules_({ user: { role: 'ADMIN' }, userId: 'OWNER' }, {
      rows: sch.map(r => ({ project_code: String(r[0]).trim(), cadre: String(r[1]).trim(),
        in_start: r[2], in_end: r[3], late_after: r[4], out_start: r[5], out_end: r[6] }))
    });
    out.push('schedules: ' + JSON.stringify(res));
  }

  resolveSectorSupervisors_();

  const summary = out.join('\n') || 'No IMPORT_* tabs found in ATTENDANCE_MASTER.';
  console.log(summary);
  return summary;
}

/**
 * Fills Sectors.supervisor_user_id from IMPORT_SECTORS.supervisor_phone once
 * the supervisor users exist. Safe to re-run any time.
 */
function resolveSectorSupervisors_() {
  const ss = masterSS_();
  const imp = ss.getSheetByName('IMPORT_SECTORS');
  if (!imp || imp.getLastRow() < 2) return;
  const sh = ss.getSheetByName('Sectors');
  const impRows = imp.getRange(2, 1, imp.getLastRow() - 1, 4).getValues();
  for (const r of impRows) {
    const scode = String(r[0]).trim();
    const phone = String(r[3] == null ? '' : r[3]).replace(/\D/g, '');
    if (!scode || !phone) continue;
    const sup = getUsersByPhone_(phone).find(u => String(u.role) === 'SUPERVISOR');
    if (!sup) continue;
    const row = findRowByValue_(sh, 1, scode);
    if (row) sh.getRange(row, 4).setValue(String(sup.user_id));
  }
  CACHE.remove('sectors');
}

///////////////////////////////////////////////////////////////////////////
//  Main.gs
///////////////////////////////////////////////////////////////////////////

/**
 * Main.gs — HTTP entry points and routing.
 *
 * All POST bodies are JSON sent as Content-Type text/plain (a CORS "simple
 * request", so the browser never preflights — Apps Script web apps cannot
 * answer OPTIONS). The session token travels in the body, never in a header.
 */

function doPost(e) {
  let req;
  try {
    req = JSON.parse(e.postData.contents);
  } catch (err) {
    return jsonOut_({ ok: false, code: 'BAD_JSON' });
  }
  try {
    const action = String(req.action || '');
    if (action === 'ping') return jsonOut_({ ok: true, ts: nowIso_() });
    if (action === 'login') return jsonOut_(apiLogin_(req));

    // Everything else requires a valid session token.
    const auth = verifyToken_(req.token);
    if (!auth.ok) return jsonOut_(auth);

    const ROUTES = {
      // field app
      sync: apiSync_,
      config: apiConfig_,
      myHistory: apiMyHistory_,
      logout: apiLogout_,
      // console (supervisor/cdpo/admin)
      nameMap: apiNameMap_,
      correction: apiCorrection_,
      pinReset: apiPinReset_,
      deviceUnbind: apiDeviceUnbind_,
      setAwcCoords: apiSetAwcCoords_,
      // console (admin)
      userUpsert: apiUserUpsert_,
      importUsers: apiImportUsers_,
      setSchedules: apiSetSchedules_,
      revoke: apiRevoke_
    };
    const fn = ROUTES[action];
    if (!fn) return jsonOut_({ ok: false, code: 'NO_ACTION' });
    return jsonOut_(fn(auth, req));
  } catch (err) {
    return jsonOut_({ ok: false, code: 'ERR', msg: String((err && err.message) || err) });
  }
}

function doGet(e) {
  const action = (e && e.parameter && e.parameter.action) || '';
  try {
    if (action === 'ping') return jsonOut_({ ok: true, ts: nowIso_() });
    if (action === 'photo') return apiPhoto_(e.parameter);
    return jsonOut_({ ok: true, service: 'attendance-backend', ts: nowIso_() });
  } catch (err) {
    return jsonOut_({ ok: false, code: 'ERR', msg: String((err && err.message) || err) });
  }
}
