#!/usr/bin/env python3
"""
build-combined.py — concatenates the backend .gs files into
backend/COMBINED.gs so deployment is a single copy-paste into the Apps
Script editor's Code.gs. Safe because Apps Script evaluates all project
files in one shared global scope anyway; only the manifest stays separate.

Re-run after ANY backend edit, commit both. Order: Util first (top-level
consts), Main last (routing) — the rest only declare functions.
"""
import hashlib
import re
import sys
from pathlib import Path

# Explicit, because evaluation order matters: Util.gs defines the constants
# every other file reads at load time, and Main.gs routes to functions the
# others define. Anything new goes in before Main.gs.
# Stock.gs and Devices.gs come after Admin.gs: both call isConsoleRole_ /
# sectorScope_ / deny_, which Admin.gs declares as top-level consts and
# functions. Function declarations hoist across the concatenation, but the
# const declarations do not, so order still matters here.
ORDER = ['Util.gs', 'Auth.gs', 'Marks.gs', 'Admin.gs', 'Stock.gs', 'Devices.gs',
         'Leaves.gs', 'Map.gs', 'Reports.gs',
         'Verify.gs', 'Summary.gs', 'DailyEmail.gs', 'Backup.gs', 'Maintenance.gs', 'Main.gs']
backend = Path(__file__).resolve().parent.parent / 'backend'

# A hardcoded list silently drops any file that is not on it, and the only
# symptom is a function the deployed project does not have. Fail loudly here
# instead: the whole point of the build is that what is on disk is what ships.
on_disk = {p.name for p in backend.glob('*.gs')} - {'COMBINED.gs'}
missing = sorted(on_disk - set(ORDER))
absent = sorted(set(ORDER) - on_disk)
if missing:
    sys.exit('BUILD FAILED: backend file(s) not in ORDER, so they would not be '
             'deployed: ' + ', '.join(missing) +
             '. Add them to ORDER in tools/build-combined.py (before Main.gs).')
if absent:
    sys.exit('BUILD FAILED: ORDER names file(s) that do not exist: ' + ', '.join(absent))

parts = []
for name in ORDER:
    src = (backend / name).read_text(encoding='utf-8')
    parts.append('\n' + '/' * 75 + f'\n//  {name}\n' + '/' * 75 + '\n\n' + src)
body = ''.join(parts)

# A fingerprint of the sources, answered by the ping route. On 2026-08-30 the
# app was found calling two deployments of this project with only one of them
# rolled; the stale one answered every request perfectly well, just with last
# week's code, and nothing could tell the two apart from outside. A content
# hash can: same sources in, same 12 characters out, so the deploy script can
# demand that EVERY endpoint the app calls is serving THIS build.
digest = hashlib.sha256(body.encode('utf-8')).hexdigest()[:12]

# The app build going out alongside this backend. finishRelease() uses it as
# the version floor, so the floor can never be a stale number somebody forgot
# to retype - it is read from the app that is actually shipping.
app_html = (Path(__file__).resolve().parents[1] / 'app' / 'index.html').read_text(encoding='utf-8')
m = re.search(r'BUILD: v[\d.]+-(\d{8}-\d{4})', app_html)
if not m:
    sys.exit('BUILD FAILED: no BUILD tag found in app/index.html.')
app_stamp = m.group(1)

header = ('/**\n * COMBINED BACKEND — generated by tools/build-combined.py. DO NOT EDIT.\n'
          ' * Edit the individual backend/*.gs files and re-run the build.\n'
          ' * Paste this whole file into Code.gs, and backend/appsscript.json\n'
          ' * into the manifest (Project Settings -> show manifest).\n */\n'
          f"const BACKEND_BUILD = '{digest}';\n"
          f"const APP_BUILD_SHIPPED = '{app_stamp}';\n")

out = backend / 'COMBINED.gs'
out.write_text(header + body, encoding='utf-8')
print(f'wrote {out} ({out.stat().st_size:,} bytes from {len(ORDER)} files, build {digest})')
