#!/usr/bin/env python3
"""
build-combined.py — concatenates the backend .gs files into
backend/COMBINED.gs so deployment is a single copy-paste into the Apps
Script editor's Code.gs. Safe because Apps Script evaluates all project
files in one shared global scope anyway; only the manifest stays separate.

Re-run after ANY backend edit, commit both. Order: Util first (top-level
consts), Main last (routing) — the rest only declare functions.
"""
from pathlib import Path

ORDER = ['Util.gs', 'Auth.gs', 'Marks.gs', 'Admin.gs', 'Leaves.gs', 'Map.gs', 'Summary.gs',
         'Maintenance.gs', 'Main.gs']
backend = Path(__file__).resolve().parent.parent / 'backend'

parts = ['/**\n * COMBINED BACKEND — generated by tools/build-combined.py. DO NOT EDIT.\n'
         ' * Edit the individual backend/*.gs files and re-run the build.\n'
         ' * Paste this whole file into Code.gs, and backend/appsscript.json\n'
         ' * into the manifest (Project Settings -> show manifest).\n */\n']
for name in ORDER:
    src = (backend / name).read_text(encoding='utf-8')
    parts.append('\n' + '/' * 75 + f'\n//  {name}\n' + '/' * 75 + '\n\n' + src)

out = backend / 'COMBINED.gs'
out.write_text(''.join(parts), encoding='utf-8')
print(f'wrote {out} ({out.stat().st_size:,} bytes from {len(ORDER)} files)')
